log_dir: ./logs/
original_dir: /share/deepfake_datasets/original/audio-video
preprocess_dir: /share/deepfake_datasets/preproocessed/audio-video
json_dir: /share/deepfake_datasets/rebuttal/json/audio-video
lmdb_dir: /share/deepfake_datasets/rebuttal/lmdb/audio-video